import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles((theme) => ({
  drawer: {
    width: "100vw",
    minHeight: "100vh",
    background: "#C3EDEC",
    position: "fixed",
    top: "0",
    left: "0",
    right: "0",
    bottom: "0",
    zIndex: "999999",
    boxSizing: "border-box",
    overflow: "hidden !important",
  },
  drawer_box: {
    margin: "20px",
    marginTop: "32px",
    boxSizing: "border-box",
    position: "relative",
    height: "calc(100vh - 32px)",
  },
  btn_div: {
    width: "100%",
    boxSizing: "border-box",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  sign_in_btn: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    maxWidth: "350px",
    position: "absolute",
    width: "100%",
    boxSizing: "border-box",
    height: "48px",
    bottom: "20px",
    background: theme.colorPlate.teal,
    borderRadius: "6px",
    border: 0,
    fontSize: "14px",
    lineHeight: "16.8px",
    color: theme.colorPlate.white,
    fontFamily: "Inter",
    fontWeight: 600,
    cursor: "pointer",
  },
  sign_out_btn: {
    ...theme.button,
    backgroundColor: theme.colorPlate.transparent,
    border: "1.5px solid rgba(55, 65, 106, 0.2)",
    color: theme.colorPlate.chaletGreen,
  },
  menuBlock: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  title: {
    fontFamily: "IBMPlexSans",
    fontWeight: 400,
    fontSize: "32px",
    lineHeight: "38.4px",
    display: "flex",
    alignItems: "center",
    color: "#1C232B",
  },
  icon_div: {
    display: "flex",
    alignItems: "center",
  },
  heartCircle: {
    height: "60px",
    width: "60px",
  },
  bellCircle: {
    height: "60px",
    width: "60px",
    marginRight: "10px",
  },
  menu: {
    listStyle: "none",
    padding: "0",
    margin: "0",
    marginTop: "17px",
    "& li": {
      margin: 0,
      marginBottom: "30px",
      padding: 0,
      fontFamily: "IBMPlexSans",
      fontWeight: 400,
      fontSize: "24px",
      lineHeight: "28.8px",
      "& a": {
        color: "#1C232B",
      },
    },
  },
  nav_selected_item: {
    color: "#21D1CC !important",
  },
}));
