import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles((theme) => ({
  /**
   * modal
   */
  paper: {
    position: "absolute",
    top: "43.5%",
    left: "50%",
    transform: `translate(-50%, -50%)`,
    width: "100%",
    maxWidth: "600px",
    height: "310px",
    backgroundColor: theme.colorPlate.white,
    boxShadow: theme.shadows[5],
    borderRadius: "20px",
    transition: "all 2s ease",
  },
  paperPadding: {
    padding: "30px 60px",
    "@media (max-width:767px)": {
      padding: "20px",
    },
  },
  modalTitle: {
    margin: "0",
    fontSize: "32px",
    fontFamily: "IBMPlexSans",
    fontWeight: 400,
    lineHeight: "38.4px",
    color: theme.colorPlate.black,
  },
  modalLabel: {
    display: "block",
    margin: "0",
    marginTop: "20px",
    fontSize: "14px",
    fontFamily: "Inter",
    fontWeight: 600,
    lineHeight: "16.8px",
    color: theme.colorPlate.black,
  },
  modalInput: {
    display: "block",
    margin: "0",
    marginTop: "6px",
    width: "100%",
    boxSizing: "border-box",
    height: "61px",
    borderRadius: "40px",
    background: theme.colorPlate.white,
    border: "1.5px solid rgba(55, 65, 106, 0.2);",
    outline: "0",
    padding: "15px 20px 16px 15px",
    fontSize: "14px",
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "19.6px",
    color: "rgba(0,0,0,0.5)",
  },
  modalInputImgCircle: {
    width: "30px",
    height: "30px",
    borderRadius: "200px",
    background: theme.colorPlate.bunker,
    border: "2px solid #E6E6E6",
  },
  modalInputCurrencyName: {
    margin: "0",
    marginLeft: "10px",
  },
  modalInputBorder: {
    width: "30px",
    height: "0",
    borderBottom: "1px solid #000000",
    opacity: "0.3",
    transform: "rotate(90deg)",
  },
  subInputModal: {
    margin: "0",
    marginLeft: "-5px",
    padding: "0",
    width: "100%",
    maxWidth: "261px",
    fontSize: "14px",
    fontFamily: "Inter",
    fontWeight: 400,
    background: "transparent",
    color: "rgba(0,0,0,0.5)",
    height: "30px",
    border: "none",
    outline: "none",
  },
  modalInputUsdPrice: {
    margin: "0",
  },
  borderTop: {
    marginTop: "30px",
    width: "100%",
    height: "0",
    borderTop: "1.5px solid rgba(55, 65, 106, 0.2);",
  },
  modalBtnDiv: {
    width: "100%",
    marginTop: "30px",
    textAlign: "end",
  },
  modalBtn: {
    width: "139px",
    height: "48px",
    borderRadius: "6px",
    background: theme.colorPlate.transparent,
    color: "#37416A",
    fontSize: "14px",
    fontFamily: "Inter",
    fontWeight: 600,
    cursor: "pointer",
    border: "1.5px solid rgba(55, 65, 106, 0.2)",
  },
  modalWidthDrawBtn: {
    width: "106px",
    marginLeft: "11px",
    background: theme.colorPlate.teal,
    color: theme.colorPlate.white,
  },
  closeBtnDiv: {
    width: "100%",
    position: "relative",
    // marginTop: "-10px",
  },
  closeBtn: {
    position: "absolute",
    top: "-10px",
    right: "-30px",
    cursor: "pointer",
    transition: "all .5s",
    "&:hover": {
      transform: "scale(1.1)",
    },
    "@media (max-width:767px)": {
      right: "0",
      top: "0",
    },
  },
  flexYCenter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
}));
