import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles((theme) => ({
  /**
   * @ flex options
   */
  flexCenterSpaceBetween: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  flexCenter: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  /**
   * @ search box
   */
  searchContainer: {
    position: "relative",
    // maxWidth: "380px",
    width: "100%",
    height: "523px",
    background: "#FFF",
    borderRadius: "20px",
  },
  searchSubContainer: {
    // maxWidth: "380px",
    width: "100%",
    height: "186px",
    background: "#F6F9F9",
    borderRadius: "20px",
    padding: "30px",
  },
  blackCircle: {
    height: "60px",
    width: "60px",
    background: theme.colorPlate.transparent,
    "& > img": {
      width: "100%",
      height: "100%",
      objectFit: "cover",
      borderRadius: "200px",
    },
  },
  name: {
    margin: "10px auto 5px auto",
    fontFamily: "IBMPlexSans",
    fontWeight: 600,
    fontSize: "18px",
    lineHeight: "21.6px",
    color: theme.colorPlate.blueCharcoal,
  },
  availableHotelsText: {
    fontFamily: "IBMPlexSans",
    fontWeight: 400,
    fontSize: "24px",
    lineHeight: "28.8px",
    color: theme.colorPlate.blueCharcoal,
    margin: "0",
  },
  bgWhite: {
    background: theme.colorPlate.white,
  },
  agentButton: {
    border: "none",
    color: "#21D1CC",
    fontFamily: "IBMPlexSans",
    fontWeight: 600,
    fontSize: "14px",
    background: theme.colorPlate.transparent,
    marginTop: "10px",
    cursor: "pointer",
  },
  searchBox: {
    padding: "30px",
  },
  label: {
    margin: "0",
    fontFamily: "IBMPlexSans",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "19.2px",
  },
  input: {
    marginTop: "11px",
    marginBottom: "19px",
    width: "100%",
    // maxWidth: "320px",
    height: "60px",
    borderRadius: "6px",
    border: "1.5px solid rgba(55, 65, 106, 0.15)",
    outline: "none",
    background: theme.colorPlate.transparent,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    "@media (max-width: 767px)": {
      background: theme.colorPlate.white,
    },
  },

  inputSearch: {
    marginTop: "11px",
    marginBottom: "19px",
    height: "60px",
    outline: "none",
    fontSize: "16px",
    fontFamily: "Inter",
    fontWeight: 400,
    background: theme.colorPlate.transparent,
  },
  searchInputBox: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: theme.colorPlate.transparent,
  },
  searchInputIcon: {
    width: "50px",
    height: "60px",
    padding: "8px",
    paddingLeft: "12px",
    marginLeft: "3px",
    borderRadius: "40px 0 0 40px",
    borderTop: "1.5px solid rgba(55, 65, 106, 0.15)",
    borderBottom: "1.5px solid rgba(55, 65, 106, 0.15)",
    borderLeft: "1.5px solid rgba(55, 65, 106, 0.15)",
    marginBottom: "3px",
    background: theme.colorPlate.transparent,
  },
  dateInput: {
    maxWidth: "110px",
    height: "58px",
    border: "none",
    borderRadius: "40px",
    outline: "none",
    // textAlign:'center'
    paddingLeft: "10px",
    fontSize: "16px",
    fontFamily: "Inter",
    fontWeight: 400,
    color: theme.colorPlate.blueCharcoal,
    background: theme.colorPlate.transparent,
  },
  dateInputTwo: {
    maxWidth: "140px",
    height: "58px",
    border: "none",
    borderRadius: "6px",
    outline: "none",
    // textAlign:'center'
    paddingLeft: "16.5px",
    fontSize: "16px",
    fontFamily: "Inter",
    fontWeight: 400,
    color: theme.colorPlate.blueCharcoal,
    background: theme.colorPlate.transparent,
  },
  calendarIcon: {
    color: theme.colorPlate.blueCharcoal,
    marginLeft: "13px",
  },
  arrowIcon: {
    fontSize: 19,
    color: theme.colorPlate.blueCharcoal,
  },
  iconLabel: {
    height: 18,
    cursor: "pointer",
  },
  searchButton: {
    ...theme.button,
    border: "none",
    fontFamily: "Inter",
    fontWeight: 600,
    fontStyle: "normal",
    fontSize: "16px",
    lineHeight: "120%",
    alignItems: "center",
    textAlign: "center",
    color: "#FFFFFF",
    cursor: "pointer",
    flexDirection: "row",
    width: "100%",
    height: "60px",
    backgroundColor: "#21D1CC",
    borderRadius: "6px",
    textTransform: "capitalize",
    boxShadow: "none",
  },
}));
