export const ERROR_MESSAGES = {
  HOTEL_NOT_FOUND: 'Hotel not found!',
  ENTER_ALL_FIELDS: 'Please enter all fields',
  CHOOSE_PAYMENT_OPTION: 'Please choose payment option',
  BOOKING_CONFIRMED: 'Booking has been confirmed'
}

export const TEXT = {
  LOGOUT: 'Logout',
  LOGIN: 'Login',
  ROOM_NUMBER: 'Room number',
  PRICE: 'Price',
  AMENITIES: 'Amenities',
  PAYMENT_OPTIONS: 'Payment options',
  CONTINUE: 'CONTINUE',
  PLEASE_CONNECT_YOUR_WALLET: 'Please connect your wallet',
  TORUS_WALLET_KOVAN: 'Torus Wallet (Kovan)',
  TORUS_WALLET_BSC: 'Torus Wallet (BSC)',
  HOTEL_DETAILS: 'Hotel Details',
  RESERVATION_DETAILS: 'Reservation Details',
  HOTELS: 'HOTELS',
  YOUR_BOOKING_IS_CONFIRMED: 'Your booking has been confirmed!',
  HOTEL_FULLY_RESERVED: 'This hotel is fully reserved',
  CURRENCY_CHOICE: 'Currency choice',
  NO_HOTEL_MACHING_FILTER: 'No hotels found matching your filters.',
  YES: 'Yes',
  NO: 'No',
  MATCHED_HOTELS: 'Matched hotels',
  FEATURED_HOTELS: 'Featured hotels',
  WHAT_ABOUT_THIS_HOTEL: 'What about this hotel?',
  AGENT_NAME: 'Agent name',
  CURRENCY: 'Currency',
  CHECKIN: 'Checkin',
  CHECKOUT: 'Checkout',
  LOCATION: 'Location',
  GUEST_COUNT: 'Guest count',
  OTHER_OFFER: 'Other offers',
  SEARCH: 'SEARCH',
  AGENT: 'AGENT',
  TOKEN: 'TOKEN',
  FILTERS: 'Filters',
  FETCH: 'FETCH',
  CREATE: 'Create',
  DEPLOY: 'Deploy',
  TRAVEL_AGENT: 'Travel agent',
  POWERED_BY_FETCH: 'powered by Fetch.ai',
  LANDING_TITLE: 'Decentralized travel',
  LANDING_SUBTITLE:
    'Creating personal digital travel agents to find, and negotiate directly with hotels on your behalf.',
  SHOW_MORE: 'SHOW MORE',
  NIGHT: 'Night',
  NIGHTS: 'nights',
  TAX: 'Tax',
  OTHER_FEES: 'Other fees',
  TOTAL: 'Total',
  BOOKING_ID: 'Booking ID',
  ADDRESS: 'Address',
  EMAIL: 'Email',
  PHONE: 'Phone',
  ROOM_TYPE: 'Room Type',
  AMOUNT: 'Amount',
  ENTER_PRICE_YOU_WANT_TO_NEGOTIATE:
    'Enter the price you want to negotiate with',
  CONFIRM: 'Confirm',
  GO_BACK_TO_SEARCH: 'Go back to search',
  AGENT_ADDRESS: 'Agent address',
  STRATEGY: 'Strategy',
  BUDGET: 'Budget',
  PEOPLE: 'People',
  NA: 'NA',
  BOOKING_DOT_COM: 'Booking.com',
  TRIVAGO: 'Trivago',
  EXPEDIA: 'Expedia',
  WHERE: 'Where',
  BUY_TRVL_TOKEN: 'BUY TRIP TOKEN',
  STAKE_TRVL: 'STAKE TRIP',
  ROOM: 'Room',
  CC: 'CC',
  CRYPTO: 'CRYPTO'
}
