import { makeStyles } from "@material-ui/core/styles";
import bannerimage7 from "../../../Assets/images/landing/landing.png";
import bannerimageSm from "../../../Assets/images/landing/landing_small.png";
import search from "../../../Assets/images/search.svg";

export const useStyles = makeStyles((theme) => ({
  root: {
    flexGrow: 1,
    fontFamily: "GTWalsheim",
    fontWeight: 400,
  },
  paper: {
    padding: theme.spacing(1),
    color: theme.palette.text.secondary,
    boxShadow: "none !important",
    background: `${theme.colorPlate.transparent}!important`,
  },
  box: {
    margin: "0 auto",
    width: "100%",
  },
  container: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    maxWidth: "1440px",
    marginLeft: "auto",
    marginRight: "auto",
    "@media (min-width:768px)": {
      padding: "0px 40px",
    },
    "@media (max-width: 767px)": {
      padding: 0,
    },
  },
  bannerblock: {
    float: "left",
    width: "100%",
    backgroundImage: `url(${bannerimage7})`,
    height: "653px",
    borderRadius: "25px",
    backgroundPosition: "center",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    marginTop: 16,
    zIndex: 1,
    "@media (max-width: 767px)": {
      height: 600,
      backgroundSize: "cover",
      marginTop: 5,
      borderRadius: 0,
      background: `linear-gradient(rgba(246, 249, 249, .2), rgba(246, 249, 249, .33) 30%), url(${bannerimageSm})`,
    },
  },
  bannerblockleft: {
    boxSizing: "border-box",
    width: "100%",
    marginTop: "15%",
    fontFamily: "Inter",
    fontWeight: 400,
    paddingLeft: "14%",
    "@media (max-width: 767px)": {
      paddingLeft: "8%",
    },
    "@media (max-width: 630px)": {
      marginTop: 65,
      padding: 10,
    },
  },
  searchhotelsection: {
    width: "100%",
    marginTop: "38px",
    "@media (max-width: 767px)": {
      display: "none",
    },
  },
  bannerblockleft1: {
    height: "24px",
    fontFamily: "IBMPlexSans",
    fontWeight: 400,
    fontStyle: "normal",
    fontSize: "24px",
    lineHeight: "120%",
    margin: 0,
    color: theme.colorPlate.blueCharcoal,
    "@media (max-width: 630px)": {
      fontSize: "20px",
      lineHeight: "21.6px",
    },
    "@media (max-width: 375px)": {
      fontSize: "18px",
      lineHeight: "21.6px",
    },
  },
  bannerblockleft2: {
    margin: 0,
    marginTop: "10px",
    fontFamily: "IBMPlexSans",
    fontWeight: 400,
    fontStyle: "normal",
    fontSize: "56px",
    lineHeight: "120%",
    color: theme.colorPlate.blueCharcoal,
    "@media (max-width: 560px)": {
      fontSize: "40px",
    },
    "@media (max-width: 375px)": {
      marginTop: 0,
    },
  },
  bannerblockRight: {
    marginTop: "10%",
    textAlign: "right",
    "& img": {
      paddingRight: "14%",
      "@media (max-width: 992px)": {
        width: "100%",
      },
    },
    "@media (max-width: 991px)": {
      display: "none",
    },
  },
  createagent_btn: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    padding: "15px 20px 16px",
    position: "absolute",
    width: "177px",
    height: "48px",
    background: theme.colorPlate.teal,
    borderRadius: "6px",
    fontFamily: "Inter",
    fontWeight: 600,
    fontStyle: "normal",
    fontSize: "14px",
    lineHeight: "120%",
    textAlign: "center",
    color: theme.colorPlate.white,
    border: "none",
    cursor: "pointer",
    "@media (max-width: 767px)": {
      display: "none",
    },
  },
  sm_search_input_input_div: {
    width: "100%",
    boxSizing: "border-box",
    padding: "0",
    maxWidth: "480px",
  },
  sm_location_search_input: {
    width: "100%",
    height: 61,
    background: theme.colorPlate.white,
    boxShadow: "0px 30px 60px rgba(0, 0, 0, 0.05)",
    borderRadius: "6px",
    outline: 0,
    border: 0,
    marginTop: 20,
    fontFamily: "IBMPlexSans",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    color: theme.colorPlate.blueCharcoal,
    alignItems: "center",
    boxSizing: "border-box",
    padding: 20,
    "&::placeholder": {
      color: theme.colorPlate.blueCharcoal,
    },
  },
  searchContainer: {
    width: "100%",
    position: "relative",
    "&:before": {
      content: "''",
      background: `url(${search})`,
      backgroundSize: "contain",
      width: "20px",
      height: "20px",
      backgroundPosition: "center center",
      position: "absolute",
      top: "50%",
      left: "20px",
      transform: "translateY(-50%)",
    },
  },
  searchInputWidth: {
    paddingLeft: "50px",
    width: "100%",
  },
  bannerblockleft3: {
    margin: 0,
    marginTop: "20px",
    maxWidth: "486.31px",
    fontFamily: "Inter",
    fontWeight: 400,
    fontStyle: "normal",
    fontSize: "20px",
    lineHeight: "140%",
    color: theme.colorPlate.blueCharcoal,
    opacity: "0.7",
    "@media (max-width: 375px)": {
      fontSize: "16px",
      lineHeight: "22.4px",
      marginTop: "10px",
      opacity: "1",
    },
  },
  bannerblockleft4: {
    marginTop: "30px",
    width: "100%",
    height: "56px",
    fontFamily: "Inter",
    fontWeight: 400,
    fontStyle: "normal",

    fontSize: "20px",
    lineHeight: "140%",
    color: theme.colorPlate.blueCharcoal,
  },
}));
