import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles((theme) => ({
  card: {
    padding: "10px 10px 20px 10px",
    color: theme.palette.text.secondary,
    borderRadius: "20px",
    backgroundColor: theme.colorPlate.white,
    height: "414px",
    minWidth: "271px",
    marginRight: "19px",
    boxSizing: "border-box",
    "&:first-child": {
      marginLeft: "0",
    },
    "&:last-child": {
      marginRight: "0",
    },
    "@media (max-width: 767px)": {
      height: "414px",
      marginRight: "10px",
    },
  },
  hotelimage: {
    width: "100%",
    height: "271px",
    borderRadius: "12px",
    objectFit: "cover",
  },
  hotel_details: {
    width: "100%",
    padding: "10px 10px 0",
    "@media (max-width: 767px)": {
      padding: "11px 10px 0",
    },
  },
  hotel_name: {
    margin: 0,
    float: "left",
    width: "100%",
    textAlign: "left",
    padding: "3px 0px",
    fontFamily: "IBMPlexSans",
    fontWeight: 600,
    fontSize: "18px",
    lineHeight: "120%",
    color: theme.colorPlate.blueCharcoal,
  },
  hotel_amenties: {
    float: "left",
    width: "100%",
    textAlign: "left",
    padding: "3px 0px",
    marginTop: "5px",
    fontFamily: "Inter",
    fontWeight: 400,
    fontStyle: "normal",

    fontSize: "13px",
    lineHeight: "120%",
    color: theme.colorPlate.blueCharcoal,
  },
  amenties_ul: {
    float: "left",
    listStyle: "none",
    width: "100%",
    padding: "0px",
    margin: "0px",
    display: "flex",
    "& > li": {
      width: "auto",
      textAlign: "left",
      fontSize: "14px",
      borderRight: "1px solid #ccc",
      paddingLeft: "10px",
      paddingRight: "10px",
      lineHeight: "10px",
      "&:first-child": {
        paddingLeft: 0,
      },
      "&:last-child": {
        borderRight: 0,
      },
    },
  },
  hotel_price: {
    float: "none",
    width: "100%",
    clear: "both",
    padding: "21px 0px 3px 0px",
    fontFamily: "GTWalsheim",
    fontWeight: 400,
  },
  hotel_price1: {
    float: "left",
    width: "70%",
    fontFamily: "IBMPlexSans",
    fontWeight: 400,
    fontSize: "22px",
    lineHeight: "120%",
    color: theme.colorPlate.blueCharcoal,
  },
  price_night: {
    fontFamily: "Inter",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "120%",
    color: theme.colorPlate.blueCharcoal,
  },
  hotel_button: {
    color: theme.colorPlate.chaletGreen,
    width: "50px",
    border: "1px solid #ccc",
    cursor: "pointer",
    height: "30px",
    padding: "0px",
    background: theme.colorPlate.white,
    boxSizing: "border-box",
    borderRadius: "5px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    "@media (max-width: 767px)": {
      width: "51.33px",
      height: "31px",
    },
  },
  hotel_arrow: {
    width: "20px",
    height: "20px",
    "@media (max-width: 767px)": {
      width: "18px",
      height: "18px",
    },
  },
}));
