import { makeStyles } from "@material-ui/core/styles";
const colorPlate = {
  dark: "#0f1920",
  white: "#fff",
  orange: "#F55035",
};
export const useStyles = makeStyles((theme) => ({
  boxWidth: {
    margin: "0 auto",
    marginTop: "60px",
    width: "100%",
    maxWidth: "1184px",
    fontFamily: "Inter",
    fontWeight: 400,
    position: "relative",
    overflowX: "hidden !important",
    "@media (max-width: 1200px)": {
      padding: "0 20px",
    },
    "@media (max-width: 960px)": {
      marginTop: "20px",
    },
  },
  title: {
    margin: "0",
    marginTop: "5px",
    fontFamily: "IBMPlexSans",
    fontWeight: 400,
    fontSize: "56px",
    lineHeight: "67.2px",
    color: "#1C232B",
    "@media (max-width: 960px)": {
      fontSize: "40px",
      lineHeight: "48px",
    },
  },
  info: {
    margin: "10px auto 0px auto",
    display: "flex",
  },
  infoCircle: {
    background: theme.colorPlate.lightGreen,
    width: "50px",
    height: "50px",
    borderRadius: "12px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginRight: "10px",
    fontFamily: "IBMPlexSans",
    fontWeight: 600,
    fontSize: "16px",
  },
  infoText: {
    marginLeft: "10px",
    marginTop: "10px",
    borderBottom: "2px solid #000",
    fontFamily: "Inter",
    fontWeight: 600,
  },
  hotelDescription: {
    marginTop: "58.5px",
    display: "flex",
    justifyContent: "space-between",
    "@media (max-width:960px)": {
      flexDirection: "column",
      marginTop: "40px",
    },
  },
  descriptionBox: {
    borderTop: "1.5px solid rgba(15, 25, 32, 0.15)",
    width: "100%",
    paddingTop: "30px",
    marginRight: "20px",
    "@media (max-width: 960px)": {
      marginRight: "0px",
    },
    "@media (max-width: 767px)": {
      paddingTop: "40px",
    },
  },
  mapLocationBox: {
    borderTop: "1.5px solid rgba(15, 25, 32, 0.15)",
    width: "100%",
    paddingTop: "30px",
    "@media (max-width:960px)": {
      marginTop: "40px",
      paddingTop: "40px",
    },
  },
  descriptionTitle: {
    margin: "0",
    fontSize: "24px",
    fontFamily: "IBMPlexSans",
    fontWeight: 400,
    lineHeight: "28.8px",
    color: "#0f1920",
  },
  descriptionText: {
    margin: "0",
    marginTop: "10px",
    fontSize: "20px",
    lineHeight: "28px",
    color: "#0f1920",
    fontFamily: "Inter",
    fontWeight: 400,
    "@media  (max-width: 767px)": {
      fontSize: "16px",
    },
    "@media (max-width:560px)": {
      lineHeight: "22.4px",
    },
    "& > p": {
      margin: "0px",
    },
  },
  featureBox: {
    marginTop: "30px",
    "@media (max-width: 767px)": {
      marginTop: "40px",
    },
  },
  featureTitle: {
    margin: "0",
    fontSize: "18px",
    lineHeight: "21.6px",
    color: "#1c232b",
    fontFamily: "IBMPlexSans",
    fontWeight: 600,
  },
  feature: {
    margin: "0",
    marginTop: "20px",
    display: "flex",
    alignItems: "center",
  },
  darkCircle: {
    maxHeight: "30px",
    maxWidth: "30px",
    minHeight: "30px",
    minWidth: "30px",
    borderRadius: "200px",
  },
  amentiesicon: {
    height: "30px",
    width: "30px",
  },
  featureName: {
    margin: "0",
    marginLeft: "10px",
    fontFamily: "Inter",
    fontWeight: 400,
    color: "#1C232B",
    fontSize: "15px",
  },
  mapLocationBoxText: {
    margin: "0",
    marginTop: "10px",
    color: "#1c232b",
    fontFamily: "Inter",
    fontWeight: 400,
    fontSize: "14px",
    "@media (max-width: 767px)": {
      fontSize: "16px",
    },
  },
  mapImage: {
    marginTop: "20px",
    width: "100%",
    height: "auto",
    borderRadius: "20px",
  },
  roomsContainer: {
    marginTop: "62px",
    borderTop: "1.5px solid rgba(15,25,32,0.15)",
    "@media (max-width: 767px)": {
      marginTop: "40px",
    },
  },
  roomsContainerTitle: {
    margin: "0",
    marginTop: "30px",
    fontSize: "24px",
    fontFamily: "IBMPlexSans",
    fontWeight: 400,
    color: "#1C232B",
    lineHeight: "28.8px",
    "@media (max-width:960px)": {
      marginTop: "40px",
    },
  },
  roomsContentContainer: {
    display: "flex",
    marginTop: "20px",
    "@media  (max-width:959px)": {
      flexDirection: "column",
      marginTop: "13px",
    },
  },
  bookingBox: {
    width: "100%",
    maxHeight: "382px",
    background: "#fff",
    borderRadius: "20px",
    marginBottom: "20px",
    "@media  (min-width: 960px)": {
      maxWidth: "380px",
      marginBottom: 0,
    },
  },
  bookingBoxMargin: {
    padding: "30px",
    "@media  (max-width: 570px)": {
      padding: "20px",
    },
  },
  bookingBoxTitle: {
    margin: "0",
    marginBottom: "20px",
    color: "#1C232B",
    fontSize: "18px",
    fontFamily: "IBMPlexSans",
    fontWeight: 600,
    "@media  (max-width: 767px)": {
      marginBottom: "22px",
    },
  },
  roomsBox: {
    marginLeft: "20px",
    "@media (max-width:959px)": {
      marginLeft: 0,
    },
  },
  room: {
    width: "780px",
    "@media (max-width:1180px)": {
      width: "100%",
    },
    height: "auto",
    borderRadius: "20px",
    background: "#fff",
    margin: "0",
    marginBottom: "10px",
    minHeight: "197px",
    boxSizing: "border-box",
    padding: "10px 10px 5px 10px",
  },
  roomBoxMargin: {
    padding: "10px 10px 10px 10px",
    display: "flex",
    "@media (max-width:1079px)": {
      flexDirection: "column",
      padding: "0 0 10px 0",
    },
  },
  roomContent: {
    width: "100%",
    padding: "0 20px",
    "@media (max-width:559px)": {
      padding: "0 10px",
    },
  },
  roomContentTitle: {
    margin: "0",
    marginTop: "10px",
    fontSize: "24px",
    lineHeight: "28.8px",
    color: "#1c232b",
    fontFamily: "IBMPlexSans",
    fontWeight: 400,
    "@media  (max-width: 767px)": {
      marginTop: "20px",
    },
  },
  roomAmenities: {
    margin: "0",
    marginTop: "5px",
    fontSize: "14px",
    lineHeight: "19.6px",
    color: "rgba(28, 35, 43, .7)",
    fontFamily: "Inter",
    fontWeight: 400,
    width: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    display: "-webkit-box",
    "-webkit-line-clamp": 2,
    "-webkit-box-orient": "vertical",
  },
  roomguests: {
    margin: "0",
    marginTop: "5px",
    fontSize: "14px",
    lineHeight: "19.6px",
    color: "#1c232b",
    fontFamily: "Inter",
    fontWeight: 400,
    width: "380px",
  },
  roomContentText: {
    display: "inline-block",
    margin: "0",
    marginTop: "16px",
    fontSize: "16px",
    fontFamily: "IBMPlexSans",
    fontWeight: 600,
    lineHeight: "19.2px",
    color: "#1c232b",
  },
  bedTypeAndButtons: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    "@media (max-width: 559px)": {
      marginTop: "10px",
      flexDirection: "column",
      alignItems: "flex-start",
    },
  },
  roomPrice: {
    fontSize: "22px",
    fontFamily: "IBMPlexSans",
    fontWeight: 400,
    color: "#1c232b",
    lineHeight: "26.4px",
    margin: "0",
    marginLeft: "5px",
    "@media (max-width: 559px)": {
      margin: "20px 0",
    },
  },
  roomTotalPrice: {
    color: "rgba(28, 35, 43, 0.7)",
    margin: "0",
    paddingRight: "8px",
    fontSize: "14px",
    lineHeight: "19.6px",
    fontFamily: "Inter",
    fontWeight: 400,
  },
  imgDiv: {
    display: "flex",
    alignItems: "center",
  },
  imgSideText: {
    margin: "0",
    marginLeft: "10px",
    fontSize: "16px",
    color: "#1C232B",
    lineHeight: "22.4px",
  },
  flex: {
    display: "flex",
  },
  flexCenter: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    position: "relative",
  },
  imageSliderMaxWidth: {
    width: "179px",
    "@media (max-width:1079px)": {
      width: "56vw",
      maxWidth: "100%",
    },
    "@media (max-width:959px)": {
      width: "100%",
      maxWidth: "100%",
    },
  },
  "slick-dots": {
    position: "absolute",
    bottom: "-25px",
    display: "block",
    width: "100%",
    padding: 0,
    margin: 0,
    listStyle: "none",
    textAlign: "center",
    "& > li": {
      position: "relative",
      color: "red",
    },
  },
  roomImage: {
    margin: "0",
    padding: "0",
    borderRadius: "12px",
    width: "100%",
    height: "179px",
    objectFit: "cover",
    outline: "none",
    "@media (max-width:1079px)": {
      height: "315px",
    },
    "@media (max-width: 959px)": {
      height: "315px",
    },
    "@media (max-width: 480px)": {
      height: "200px",
    },
  },
  hotelBookButtonsContainer: {
    display: "flex",
    marginTop: "6px",
    "@media (max-width: 559px)": {
      width: "100%",
    },
  },
  negotiateBtn: {
    ...theme.button,
    width: "107px",
    height: "48px",
    borderRadius: "6px",
    backgroundColor: "#37416A",
    border: "none",
    fontFamily: "Inter",
    fontWeight: 600,
    color: "#F5F9FD",
    cursor: "pointer",
    "&:hover": {
      background: "#21D1CC",
    },
    "@media (max-width: 559px)": {
      width: "100%",
    },
    "@media (max-width: 375px)": {
      maxWidth: "107px",
    },
  },
  bookNowBtn: {
    ...theme.button,
    width: "107px",
    height: "48px",
    borderRadius: "6px",
    backgroundColor: "#21D1CC",
    border: "none",
    fontFamily: "Inter",
    fontWeight: 600,
    cursor: "pointer",
    color: "#F5F9FD",
    marginLeft: "10px",
    "@media (max-width: 559px)": {
      width: "100%",
    },
  },
  roomSeeMoreButton: {
    ...theme.button,
    width: "100%",
    height: "48px",
    borderRadius: "6px",
    border: "1.5px solid rgba(55, 65, 106, 0.2)",
    color: "#37416A",
    fontSize: "14px",
    lineHeight: "16.8px",
    fontFamily: "Inter",
    fontWeight: 600,
    backgroundColor: theme.colorPlate.transparent,
    boxShadow: "none",
    textAlign: "center",
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    "&:hover": {
      backgroundColor: theme.colorPlate.chaletGreen,
      color: "#fff",
    },
    "&:disabled": {
      backgroundColor: "#cccccc",
    },
  },
  roomBoxButton: {
    width: "100%",
    height: "48px",
    borderRadius: "6px",
    border: "1.5px solid rgba(55, 65, 106, 0.15)",
    color: "#37416A",
    fontSize: "14px",
    lineHeight: "16.8px",
    fontFamily: "IBMPlexSans",
    fontWeight: 600,
    padding: "15px 55px 16px 0px",
    background: theme.colorPlate.white,
    textAlign: "center",
    cursor: "pointer",
    "&:hover": {
      background: "#F5F9FD",
    },
  },
  label: {
    margin: "0",
    fontFamily: "IBMPlexSans",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "19.2px",
    color: theme.colorPlate.black,
  },
  input: {
    marginTop: "8px",
    marginBottom: "19px",
    width: "100%",
    height: "60px",
    borderRadius: "6px",
    border: "1.5px solid rgba(55, 65, 106, 0.15)",
    outline: "none",
    backgroundColor: "transparent !important",
  },
  dateInput: {
    maxWidth: "100px",
    height: "58px",
    border: "none",
    borderRadius: "40px",
    outline: "none",
    fontSize: "16px",
    fontFamily: "Inter",
    fontWeight: 400,
    color: "#1C232B",
    backgroundColor: theme.colorPlate.transparent,
  },
  dateInputTwo: {
    maxWidth: "119px",
    height: "58px",
    border: "none",
    borderRadius: "40px",
    outline: "none",
    fontSize: "16px",
    fontFamily: "Inter",
    fontWeight: 400,
    color: "#1C232B",
    backgroundColor: theme.colorPlate.transparent,
  },
  iconLabel: {
    height: 18,
    cursor: "pointer",
  },
  paddingRight10: {
    paddingRight: "10px",
  },
  paddingRight16_5: {
    paddingRight: "16.5px",
  },
  // filterButton
  filterIcon: {
    width: "16px",
    height: "20px",
  },
  filterButton: {
    marginTop: "11px",
    marginBottom: "20px",
    width: "100%",
    height: "60px",
    border: "1.5px solid rgba(55, 65, 106, 0.15)",
    borderRadius: "6px",
    fontFamily: "Inter",
    fontWeight: 400,
    fontSize: "16px",
    color: "#1C232B",
    backgroundColor: "transparent",
    padding: "0 13px",
  },
  filterCounterButton: {
    width: "20px",
    height: "20px",
    border: "2px solid rgba(55, 65, 106, 1)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "200px",
    cursor: "pointer",
    backgroundColor: "transparent",
  },
  filterCounterButtonDisabled: {
    width: "20px",
    height: "20px",
    border: "2px solid rgba(55, 65, 106, .3)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "200px",
    cursor: "not-allowed",
  },
  searchButton: {
    background: "#21D1CC",
    height: "60px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    border: "none",
    borderRadius: "6px",
    color: "#f5f9fd",
    fontFamily: "IBMPlexSans",
    fontWeight: 600,
    fontSize: "16px",
    cursor: "pointer",
    textTransform: "capitalize",
    boxShadow: "none",
  },
  reviewSection: {
    borderTop: "1.5px solid rgba(15, 25, 32, 0.15)",
    marginTop: "80px",
  },
  reviewSectionTitle: {
    margin: "0",
    marginTop: "30px",
    fontSize: "24px",
    color: "#1C232B",
    lineHeight: "28.8px",
    fontFamily: "IBMPlexSans",
    fontWeight: 400,
  },
  reviewSectionSubTitle: {
    margin: "0",
    marginTop: "10px",
    fontSize: "14px",
    lineHeight: "19.6px",
    color: "#1c232b",
    fontFamily: "Inter",
    fontWeight: 400,
  },
  commentBox: {
    width: "580px",
    height: "128px",
    marginTop: "20px",
  },
  commentImgCircle: {
    width: "60px",
    height: "60px",
    background: "rgba(229, 229, 229, 1)",
    borderRadius: "200px",
  },
  comment: {
    width: "508px",
    height: "128px",
    background: "#e6e6e6",
    marginLeft: "12px",
    borderRadius: "0 20px 20px 20px",
  },
  commentMargin: {
    margin: "20px",
  },
  commentUserName: {
    fontSize: "13px",
    fontFamily: "Inter",
    fontWeight: 600,
    color: "#1C232B",
    lineHeight: "15.6px",
    margin: "0",
    marginTop: "25px",
  },
  commentUserNameSpan: {
    color: "rgba(28, 35, 43, 0.5)",
  },
  commentText: {
    fontSize: "16px",
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "22.4px",
    margin: "0",
    marginTop: "5px",
    color: "#1C232B",
  },
  starDiv: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginTop: "12px",
  },
  starNumber: {
    margin: "0 3px 0 4px",
    fontSize: "18px",
    fontFamily: "IBMPlexSans",
    fontWeight: 600,
  },
  favIconStyle: {
    color: "#FD7269",
    fontSize: "20px",
    cursor: "pointer",
  },
  commentStarIcon: {
    fontSize: "15px",
  },
  reviewSectionButton: {
    width: "116px",
    height: "38px",
    borderRadius: "40px",
    border: "1.5px solid rgba(55, 65, 106, 0.15)",
    color: colorPlate.orange,
    background: theme.colorPlate.white,
    margin: "0",
    marginTop: "22px",
    fontFamily: "IBMPlexSans",
    fontWeight: 600,
    fontSize: "14px",
    cursor: "pointer",
  },
  similarHotelsSection: {
    marginTop: "120px",
    "@media (max-width: 959px)": {
      marginTop: "40px",
      paddingTop: "40px",
      borderTop: "1.5px solid rgba(55, 65, 106, .15)",
    },
  },
  shsTitleDiv: {
    marginLeft: "21px",
    "@media  (max-width: 559px)": {
      marginLeft: "15px",
    },
  },
  shsSmallTitle: {
    fontSize: "16px",
    fontFamily: "IBMPlexSans",
    fontWeight: 400,
    lineHeight: "19.2px",
    color: "#1C232B",
    margin: "0",
    "@media  (max-width: 559px)": {
      fontSize: "14px",
      lineHeight: "16.8px",
    },
  },
  shsBigTitle: {
    fontSize: "40px",
    fontFamily: "IBMPlexSans",
    fontWeight: 400,
    lineHeight: "48px",
    color: "#1C232B",
    margin: "0",
    "@media  (max-width: 559px)": {
      fontSize: "24px",
      lineHeight: "28.8px",
    },
  },
  similarHotelCard: {
    width: "500px",
    marginTop: "30px",
    color: "red",
    borderRadius: "20px",
  },
  hotelCard: {
    width: "281px",
    height: "404px",
    background: "#fff",
    borderRadius: "20px",
    margin: "0",
    marginTop: "30px",
    marginRight: "20px",
    marginBottom: "100px",
    "@media (max-width:767px)": {
      marginBottom: "40px",
    },
  },
  hotelCardPadding: {
    padding: "10px",
  },
  shsHotelCardImage: {
    width: "261px",
    height: "271px",
    borderRadius: "12px",
    background: "#0f1920",
  },
  shsHotelCardBody: {
    padding: "0 10px",
  },
  shsHotelCardName: {
    margin: "0",
    marginTop: "15px",
    fontFamily: "Inter",
    fontWeight: 600,

    fontSize: "18px",
    lineHeight: "21.6px",
    color: "#1C232B",
  },
  shsHotelCardAmenities: {
    margin: "0",
    marginTop: "5px",
    paddingRight: "14px",
    fontSize: "13px",
    lineHeight: "15.6px",
    color: "#1c232b",
    display: "inline-block",
  },
  borderLeft: {
    paddingLeft: "12px",
    paddingRight: "12px",
    borderLeft: "1px solid rgba(28, 35, 43, 0.15)",
  },
  shsHotelCardPrice: {
    fontSize: "22px",
    fontFamily: "Inter",
    fontWeight: 400,
    color: "#1c232b",
    lineHeight: "26.4px",
    margin: "0",
    marginTop: "17px",
  },
  shsHotelCardPriceText: {
    marginLeft: "5px",
    fontSize: "12px",
  },
  shsHotelCardButton: {
    width: "51.33px",
    height: "31px",
    border: "1.5px solid rgba(55, 65, 106, 0.2)",
    color: "#37416A",
    borderRadius: "6px",
    marginTop: "14px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    background: theme.colorPlate.transparent,
  },
  flexCenterSpaceBetween: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  marginLeft20: {
    marginLeft: "20px",
  },
  calendarIcon: {
    color: theme.colorPlate.blueCharcoal,
    marginLeft: "19px",
    "@media (max-width: 767px)": {
      marginLeft: "10px",
    },
  },
  guest_field1: {
    float: "left",
    width: "12%",
    padding: "5px",
    marginTop: "13px",
  },
  guest_field2: {
    float: "left",
    width: "50%",
  },
  guest_input: {
    width: "90%",
    border: "1.5px solid rgba(55, 65, 106, 0.15)",
    height: "50px",
    outline: "none",
    marginTop: "11px",
    borderRadius: "40px",
    marginBottom: "19px",
    paddingLeft: "15px",
  },
  add_btn: {
    float: "left",
    width: "100%",
  },
  guest_select: {
    padding: "14px",
    background: "#fff",
    border: "1px solid #ccc",
  },
  addguestbox: {
    background: "#e7e7e7",
    float: "left",
    borderRadius: "20px",
    padding: "10px",
    width: "97%",
  },
  guestbox: {
    display: "flex",
    justifyContent: "space-between",
  },
  addguestbox_container: {
    float: "left",
    width: "100%",
    padding: "5px",
  },
  guest_label: {
    color: "#000000",
    margin: "0",
    display: "block",
    fontSize: "14px",
    fontFamily: "Inter",
    fontWeight: 600,
    lineHeight: "16.8px",
  },
  accordion: {
    backgroundColor: "transparent",
    border: 0,
    boxShadow: "none",
    "& .Mui-expanded": {
      height: "48px",
      minHeight: " 48px",
      maxHeight: " 48px",
    },
  },
  accordionSummary: {
    padding: "0 16px 0 0",
    "& .Mui-expanded": {
      margin: "12px -12px 12px 0",
      alignItems: "center",
    },
    "& .MuiTouchRipple-root": {
      display: "none",
    },
  },
  loading_text: {
    display: "flex",
    alignItems: "center",
  },
  similar_hotels_container: {
    width: "100%",
    maxWidth: "1180px",
    margin: "60px auto 120px",
    "@media (max-width: 767px)": {
      margin: "40px 0",
    },
    "& .root": {
      margin: 0,
    },
    "& .bestoffers_heading_padding": {
      padding: "0 17px 0 19px",
    },
    "& .bestOfferIcon": {
      margin: "0",
      marginRight: "15px",
    },
  },
  borderTop: {
    margin: "0 20px",
    borderTop: "1.5px solid rgba(55, 65, 106, .15)",
    paddingTop: "30px",
    "@media (max-width: 767px)": {
      paddingTop: "40px",
    },
  },
}));
