import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles((theme) => ({
  card: {
    width: 500,
    minHeight: 500,
    backgroundColor: "#fff",
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    borderRadius: "20px",
  },
  title: {
    margin: "0px",
    padding: "20px",
    textAlign: "center",
    fontFamily: "IBMPlexSans",
    fontWeight: 400,
    borderBottom: "1px solid #c4edec",
    background: "#c4edec",
    fontSize: "20px",
  },
  cancel_ul: {
    margin: "0px",
    padding: "0",
  },
  cancel_li: {
    margin: "8px",
  },
  title1: {
    padding: "10px",
    textAlign: "center",
    fontFamily: "IBMPlexSans",
    fontWeight: 500,
    margin: "0px",
  },
  paper: {
    position: "absolute",
    top: "46.5%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    maxWidth: 400,
    backgroundColor: "#C3EDEC",
    border: "0",
    borderRadius: 20,
    boxShadow: theme.shadows[5],
    textAlign: "center",
    overflow: "hidden",
    width: "100%",
    paddingBottom: "50px",
  },

  modalTitle: {
    margin: "0",
    marginTop: "20px",
    fontSize: "40px",
    fontFamily: "IBMPlexSans",
    fontWeight: 400,
    lineHeight: "48px",
    color: theme.colorPlate.blueCharcoal,
  },
  modalDescription: {
    margin: "0 auto",
    marginTop: "5px",
    maxWidth: "317px",
    fontSize: "16px",
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "22.4px",
    color: theme.colorPlate.blueCharcoal,
    opacity: "0.7",
  },
  modalFooter: {
    margin: "0 auto",
    marginTop: "30px",
    width: "100%",
    background: "#ECF4F4",
    boxSizing: "border-box",
    padding: "30px 40px",
  },
  modalButton: {
    height: "48px",
    padding: "15px 20px 16px",
    border: "0",
    borderRadius: "6px",
    background: theme.colorPlate.green,
    color: theme.colorPlate.white,
    fontSize: "14px",
    fontFamily: "Inter",
    fontWeight: 600,
    lineHeight: "16.8px",
    cursor: "pointer",
    width: "100%",
  },
}));
